class Hotel{
  String name;
  String image;
  String description;
  String type;
  String category;
  double rating;
  int reviews;
  int price;

  Hotel({
    required this.name,
    required this.image,
    required this.description,
    required this.type,
    required this.category,
    required this.rating,
    required this.reviews,
    required this.price,
  });
}

List<Hotel> listHotel = [
  Hotel(
    name: 'Chateau Blanc',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/179959261.jpg?k=ce42e5092a257aef6bbfb893ff4325aeaa1d583dd187f08d3e21f563e01f0152&o=&hp=1',
    description: 'Chateau Blanc Unit 7 offers accommodations in Aspen, 3.7 miles from Independence Pass and 2.3 miles from Aspen Golf and Tennis Club. It is located a 9-minute walk from The John Denver Sanctuary and provides free Wifi plus free shuttle service.\n\nThe vacation home has a cable TV. The vacation home also offers a well-equipped kitchen with a microwave, a toaster and a fridge, a seating area, as well as a bathroom with a shower and a hair dryer.\n\nSkiing can be enjoyed nearby.',
    type: '3N/2D',
    category: 'Exceptional',
    rating: 4.9,
    reviews: 312,
    price: 320,
  ),
  Hotel(
    name: 'Limelight Hotel',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/374058309.jpg?k=c0ad83ac7a86ace71476c705d5704b67c3cd00330f9e09ae1c6eccfcf0e829f7&o=&hp=1',
    description: 'Within walking distance of Aspen Mountain, Limelight Hotel features guest rooms with free Wi-Fi and 32-inch flat-screen cable TVs. This Colorado hotel has an outdoor pool, hot tub and rooftop terrace.\n\nThe guest rooms provide iPod docking stations and laptop safes. They also have seating areas, desks and ironing facilities.\n\nLimelight Hotel serves breakfast and offers a ski guide service and gym. A business center and meeting rooms are also available.\n\nThe Limelight Hotel is in a great location across from Wagner Park and is less than a half mile from Aspen Art Museum. It is 3 miles from Buttermilk Mountain Ski Area and 10 miles from Krabloonik Dogsled Rides.\n\nThis is our guests\' favorite part of Aspen, according to independent reviews.',
    type: '2N/2D',
    category: 'Exceptional',
    rating: 4.9,
    reviews: 200,
    price: 360,
  ),
  Hotel(
    name: 'Square Hotel',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/177962454.jpg?k=2af9517a7f6428f6e6b38560dc0f37e69cd378267deab1990785657401ab92c8&o=&hp=1',
    description: 'A 6-minute walk from The John Denver Sanctuary, Independence Square Unit 203 is located in Aspen and has free WiFi and concierge services. The property is around 3.9 miles from Independence Pass, 2.2 miles from Aspen Golf and Tennis Club and 8 miles from Snowmass Club Golf Course.\n\nThe rooms at the hotel come with air conditioning, a seating area, a TV with cable channels, a kitchen, a dining area and a private bathroom with a hairdryer and a shower. All guest rooms will provide guests with a closet and a coffee machine.',
    type: '1N/2D',
    category: 'Exceptional',
    rating: 4.8,
    reviews: 120,
    price: 290,
  ),
  Hotel(
    name: 'The Gant',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/34093269.jpg?k=c59abc2f44b89feadd310da1eca8bcf6db3790f2833639a56ab06c151c133889&o=&hp=1',
    description: 'Located near the base of Aspen Mountain and 5 minutes\' walk from the Aspen Skiing Company, this resort offers year-round outdoor pools and hot tubs. Rooms feature free WiFi.\n\nThe accommodations at The Gant include a wood burning fireplace and a private balcony.  The kitchen is complete with a stovetop, oven, and dishwasher.  Cookware and dishware are provided.\n\nThis Aspen resort hosts an on-site fitness center and 5 tennis courts. A free shuttle service to/from Aspen-Pitkin County Airport and Aspen attractions is provided upon request. Concierge and child care services are available.  Ski storage and tuning are offered.',
    type: '3N/2D',
    category: 'Wonderful',
    rating: 4.7,
    reviews: 210,
    price: 275,
  ),
  Hotel(
    name: 'Timber Ridge',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/334191234.jpg?k=ee1ed1434c659fa2ec065c3b571fb422781fc6d4faeaabdd7b57a38909390032&o=&hp=1',
    description: 'Located near the base of Aspen Mountain and 5 minutes\' walk from the Aspen Skiing Company, this resort offers year-round outdoor pools and hot tubs. Rooms feature free WiFi.\n\nThe accommodations at The Gant include a wood burning fireplace and a private balcony.  The kitchen is complete with a stovetop, oven, and dishwasher.  Cookware and dishware are provided.\n\nThis Aspen resort hosts an on-site fitness center and 5 tennis courts. A free shuttle service to/from Aspen-Pitkin County Airport and Aspen attractions is provided upon request. Concierge and child care services are available.  Ski storage and tuning are offered.',
    type: '1N/1D',
    category: 'Wonderful',
    rating: 4.6,
    reviews: 170,
    price: 260,
  ),
  Hotel(
    name: 'Mountain Lodge',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/393995183.jpg?k=9328c791ebdc9bd8f5bd2d797990c2429564b67ad8fa3c00d191a02859a319ec&o=&hp=1',
    description: 'Aspen Mountain Lodge 402 has a balcony and is located in Aspen, within just a 11-minute walk of The John Denver Sanctuary and 0.7 miles of Aspen Art Museum. It features a garden, mountain views and free Wifithroughout the property.\n\nThe vacation home has a cable TV. Featuring an a bath or shower, the bathroom also offers bathrobes, and towels and bed linen are available.\n\nSkiing and cycling can be enjoyed nearby.',
    type: '2N/2D',
    category: 'Wonderful',
    rating: 4.7,
    reviews: 827,
    price: 370,
  ),
  Hotel(
    name: 'Concept 600',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/303736045.jpg?k=c014eba3ff8aec4b087ac0fbdd0b27203c5bd1866d4770b0f4b91aad7223147d&o=&hp=1',
    description: 'Featuring air conditioning, Concept 600 Condominiums by Frias is located in Aspen, 656 feet from Aspen Mountain Ajax. The accommodations features a hot tub. The John Denver Sanctuary is 1640 feet away.\n\nThere is also a kitchen, fitted with a dishwasher. Towels are offered.\n\nConcept 600 Condominiums by Frias also includes a hot tub.',
    type: '2N/1D',
    category: 'Very Good',
    rating: 4.5,
    reviews: 120,
    price: 190,
  ),
  Hotel(
    name: 'Aspen Stash',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/399614155.jpg?k=5e579b3128f98a58b15a9106c54ae173971274816a68afeaaaeacbc24d5b797b&o=&hp=1',
    description: 'Located in Aspen and only a 12-minute walk from The John Denver Sanctuary, Aspen Stash Pad with Fireplace, Parking, W/D has accommodations with mountain views, free Wifi and free private parking. This apartment is 3.9 miles from Independence Pass and 2.5 miles from Aspen Golf and Tennis Club.\n\nThe apartment is equipped with 1 separate bedroom, 1 bathroom, a fully equipped kitchen with a dining area and dishwasher, and a living room with a flat-screen TV. Towels and bed linen are offered in the apartment.',
    type: '2N/2D',
    category: 'Very Good',
    rating: 4.6,
    reviews: 372,
    price: 285,
  ),
  Hotel(
    name: 'The Little Nell',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/284678034.jpg?k=cd2b25c20f3c938ea9f40e5c9e65ae55ebe8d21a8167332e94b68f8ee061b5ec&o=&hp=1',
    description: 'This luxurious mountain hotel is the only hotel in the heart of Aspen that boasts ski-to-door access. It features an on site restaurant with an award-wining wine list and a tavern on-site. Summer, Fall, and Winter activities are all available from the property.\n\nFree Wi-Fi is offered in all rooms at The Little Nell.  Each spacious room includes a flat-screen cable TV, an iPod docking station, a fireplace and a minibar, which includes non-alcoholic beverages and snacks.  Rooms offer either city or mountain views.',
    type: '1N/2D',
    category: 'Very Good',
    rating: 4.6,
    reviews: 172,
    price: 250,
  ),
  Hotel(
    name: 'Alpenblick',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/179959441.jpg?k=2fc2a3a1d163e14efc73cc00ff45194f7d29c6854c2ce791fcd009e0da87db0e&o=&hp=1',
    description: 'Alpenblick Unit 1 enjoys a location in Aspen, just 4.1 miles from Independence Pass and 2.2 miles from Aspen Golf and Tennis Club. It is located a 10-minute walk from The John Denver Sanctuary and has free Wifi plus free shuttle service.\n\nThe vacation home is equipped with 3 separate bedrooms, 2 bathrooms, a fully equipped kitchen with a dining area and microwave, and a living room with a TV.',
    type: '3N/2D',
    category: 'Good',
    rating: 4.6,
    reviews: 189,
    price: 200,
  ),
  Hotel(
    name: 'Cottonwoods',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/318221760.jpg?k=cea6152b70f19ed516bfd59412fbd810c9ba624d9f8606f411003e61a8f67198&o=&hp=1',
    description: 'Cottonwoods Unit 3D in Aspen provides accommodations with free Wifi, a 11-minute walk from The John Denver Sanctuary, 4.3 miles from Independence Pass and a 8-minute walk from Aspen Art Museum. This vacation home is 1.7 miles from Aspen Golf and Tennis Club and 7.5 miles from Snowmass Club Golf Course.\n\nThe air-conditioned vacation home also has a TV, a seating area, washing machine and a bathroom with a shower.\n\nIf you would like to discover the area, skiing is possible nearby.',
    type: '3N/2D',
    category: 'Good',
    rating: 4.5,
    reviews: 910,
    price: 325,
  ),
  Hotel(
    name: 'Old Hundred',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/327872829.jpg?k=2491ab3249c68aca9b3dc8617eac59507ad3395052c330ed7182f5a0784afbfa&o=&hp=1',
    description: 'Old Hundred Unit 104 offers accommodations in Aspen, 3.7 miles from Independence Pass and 2.4 miles from Aspen Golf and Tennis Club. It is located a 10-minute walk from The John Denver Sanctuary and has free Wifi plus free shuttle service.\n\nThe air-conditioned vacation home also provides a TV, a fully equipped kitchen with a microwave, a seating area, washing machine and a bathroom with a shower.',
    type: '1N/1D',
    category: 'Good',
    rating: 4.7,
    reviews: 728,
    price: 240,
  ),
  Hotel(
    name: 'Regis Ressort',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/388329427.jpg?k=0f15b4b8f894ad53e3fa6da54ba9572eb2433092a38f5065314ee341d93d05ba&o=&hp=1',
    description: 'Featuring air-conditioned accommodations with a heated pool, St Regis Aspen Resort - King Hotel Room is located in Aspen. This apartment provides free private parking and an elevator.\n\nWith free Wifi, this apartment has a satellite TV and a kitchen with a microwave and toaster.\n\nPopular points of interest near the apartment include The John Denver Sanctuary, Aspen Art Museum and Mill Street Fountain. The nearest airport is Aspen-Pitkin County Airport, 3.1 miles from St Regis Aspen Resort - King Hotel Room.',
    type: '2N/2D',
    category: 'Pleasent',
    rating: 4.8,
    reviews: 782,
    price: 320,
  ),
  Hotel(
    name: 'Chic Condo',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/326565630.jpg?k=ea1746a0f7066fbc1f158e61975edde16bf8a5d344ec005f124960b1ebeee1a3&o=&hp=1',
    description: 'Chic Condo Unit 1 has accommodations with free WiFi in Aspen, ideally set a 8-minute walk from Aspen Art Museum and 0.6 miles from Isis Theatre. The property is around 3.6 miles from Independence Pass, a 11-minute walk from Mill Street Fountain and 2.5 miles from Aspen Golf and Tennis Club. The property is non-smoking throughout and is located a 11-minute walk from The John Denver Sanctuary.\n\nThe rooms at the hotel come with a fridge, a dishwasher, a coffee machine, a bath or shower, free toiletries, a TV with cable channels and DVD player. Guest rooms have a private bathroom, a hairdryer and bed linen.',
    type: '3N/2D',
    category: 'Pleasent',
    rating: 4.7,
    reviews: 829,
    price: 295,
  ),
  Hotel(
    name: 'Luxurious',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/465288867.jpg?k=e59b50776354bf7d758b2a943d6ff696933db4979a709b0a3e5127e115804718&o=&hp=1',
    description: 'Luxurious 2 BR, 2 BA - Aspen Core has a patio and is located in Aspen, within just a 3-minute walk of Aspen Art Museum and 300 yards of Isis Theatre. The property is a 4-minute walk from the The John Denver Sanctuary and features free Wifithroughout the property.\n\nThe vacation home features 2 bedrooms, a fully equipped kitchen with a dishwasher and an oven, and 2 bathrooms with a hot tub and a hair dryer. Towels and bed linen are featured in the vacation home.',
    type: '2N/1D',
    category: 'Pleasent',
    rating: 4.8,
    reviews:288,
    price: 280,
  ),
];

List<Hotel> listHotelRecom = [
  Hotel(
    name: 'Square Hotel',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/177962454.jpg?k=2af9517a7f6428f6e6b38560dc0f37e69cd378267deab1990785657401ab92c8&o=&hp=1',
    description: 'A 6-minute walk from The John Denver Sanctuary, Independence Square Unit 203 is located in Aspen and has free WiFi and concierge services. The property is around 3.9 miles from Independence Pass, 2.2 miles from Aspen Golf and Tennis Club and 8 miles from Snowmass Club Golf Course.\n\nThe rooms at the hotel come with air conditioning, a seating area, a TV with cable channels, a kitchen, a dining area and a private bathroom with a hairdryer and a shower. All guest rooms will provide guests with a closet and a coffee machine.',
    type: '1N/2D',
    category: 'Exceptional',
    rating: 4.8,
    reviews: 120,
    price: 290,
  ),
  Hotel(
    name: 'The Gant',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/34093269.jpg?k=c59abc2f44b89feadd310da1eca8bcf6db3790f2833639a56ab06c151c133889&o=&hp=1',
    description: 'Located near the base of Aspen Mountain and 5 minutes\' walk from the Aspen Skiing Company, this resort offers year-round outdoor pools and hot tubs. Rooms feature free WiFi.\n\nThe accommodations at The Gant include a wood burning fireplace and a private balcony.  The kitchen is complete with a stovetop, oven, and dishwasher.  Cookware and dishware are provided.\n\nThis Aspen resort hosts an on-site fitness center and 5 tennis courts. A free shuttle service to/from Aspen-Pitkin County Airport and Aspen attractions is provided upon request. Concierge and child care services are available.  Ski storage and tuning are offered.',
    type: '3N/2D',
    category: 'Wonderful',
    rating: 4.7,
    reviews: 210,
    price: 275,
  ),
  Hotel(
    name: 'Aspen Stash',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/399614155.jpg?k=5e579b3128f98a58b15a9106c54ae173971274816a68afeaaaeacbc24d5b797b&o=&hp=1',
    description: 'Located in Aspen and only a 12-minute walk from The John Denver Sanctuary, Aspen Stash Pad with Fireplace, Parking, W/D has accommodations with mountain views, free Wifi and free private parking. This apartment is 3.9 miles from Independence Pass and 2.5 miles from Aspen Golf and Tennis Club.\n\nThe apartment is equipped with 1 separate bedroom, 1 bathroom, a fully equipped kitchen with a dining area and dishwasher, and a living room with a flat-screen TV. Towels and bed linen are offered in the apartment.',
    type: '2N/2D',
    category: 'Very Good',
    rating: 4.6,
    reviews: 372,
    price: 285,
  ),
  Hotel(
    name: 'Alpenblick',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/179959441.jpg?k=2fc2a3a1d163e14efc73cc00ff45194f7d29c6854c2ce791fcd009e0da87db0e&o=&hp=1',
    description: 'Alpenblick Unit 1 enjoys a location in Aspen, just 4.1 miles from Independence Pass and 2.2 miles from Aspen Golf and Tennis Club. It is located a 10-minute walk from The John Denver Sanctuary and has free Wifi plus free shuttle service.\n\nThe vacation home is equipped with 3 separate bedrooms, 2 bathrooms, a fully equipped kitchen with a dining area and microwave, and a living room with a TV.',
    type: '3N/2D',
    category: 'Good',
    rating: 4.6,
    reviews: 189,
    price: 200,
  ),
  Hotel(
    name: 'Regis Ressort',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/388329427.jpg?k=0f15b4b8f894ad53e3fa6da54ba9572eb2433092a38f5065314ee341d93d05ba&o=&hp=1',
    description: 'Featuring air-conditioned accommodations with a heated pool, St Regis Aspen Resort - King Hotel Room is located in Aspen. This apartment provides free private parking and an elevator.\n\nWith free Wifi, this apartment has a satellite TV and a kitchen with a microwave and toaster.\n\nPopular points of interest near the apartment include The John Denver Sanctuary, Aspen Art Museum and Mill Street Fountain. The nearest airport is Aspen-Pitkin County Airport, 3.1 miles from St Regis Aspen Resort - King Hotel Room.',
    type: '2N/2D',
    category: 'Pleasent',
    rating: 4.8,
    reviews: 782,
    price: 320,
  ),
];

List<Hotel> listHotelFav = [
  Hotel(
    name: 'Limelight Hotel',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/374058309.jpg?k=c0ad83ac7a86ace71476c705d5704b67c3cd00330f9e09ae1c6eccfcf0e829f7&o=&hp=1',
    description: 'Within walking distance of Aspen Mountain, Limelight Hotel features guest rooms with free Wi-Fi and 32-inch flat-screen cable TVs. This Colorado hotel has an outdoor pool, hot tub and rooftop terrace.\n\nThe guest rooms provide iPod docking stations and laptop safes. They also have seating areas, desks and ironing facilities.\n\nLimelight Hotel serves breakfast and offers a ski guide service and gym. A business center and meeting rooms are also available.\n\nThe Limelight Hotel is in a great location across from Wagner Park and is less than a half mile from Aspen Art Museum. It is 3 miles from Buttermilk Mountain Ski Area and 10 miles from Krabloonik Dogsled Rides.\n\nThis is our guests\' favorite part of Aspen, according to independent reviews.',
    type: '2N/2D',
    category: 'Exceptional',
    rating: 4.9,
    reviews: 200,
    price: 360,
  ),
  Hotel(
    name: 'The Gant',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/34093269.jpg?k=c59abc2f44b89feadd310da1eca8bcf6db3790f2833639a56ab06c151c133889&o=&hp=1',
    description: 'Located near the base of Aspen Mountain and 5 minutes\' walk from the Aspen Skiing Company, this resort offers year-round outdoor pools and hot tubs. Rooms feature free WiFi.\n\nThe accommodations at The Gant include a wood burning fireplace and a private balcony.  The kitchen is complete with a stovetop, oven, and dishwasher.  Cookware and dishware are provided.\n\nThis Aspen resort hosts an on-site fitness center and 5 tennis courts. A free shuttle service to/from Aspen-Pitkin County Airport and Aspen attractions is provided upon request. Concierge and child care services are available.  Ski storage and tuning are offered.',
    type: '3N/2D',
    category: 'Wonderful',
    rating: 4.7,
    reviews: 210,
    price: 275,
  ),
  Hotel(
    name: 'Aspen Stash',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/399614155.jpg?k=5e579b3128f98a58b15a9106c54ae173971274816a68afeaaaeacbc24d5b797b&o=&hp=1',
    description: 'Located in Aspen and only a 12-minute walk from The John Denver Sanctuary, Aspen Stash Pad with Fireplace, Parking, W/D has accommodations with mountain views, free Wifi and free private parking. This apartment is 3.9 miles from Independence Pass and 2.5 miles from Aspen Golf and Tennis Club.\n\nThe apartment is equipped with 1 separate bedroom, 1 bathroom, a fully equipped kitchen with a dining area and dishwasher, and a living room with a flat-screen TV. Towels and bed linen are offered in the apartment.',
    type: '2N/2D',
    category: 'Very Good',
    rating: 4.6,
    reviews: 372,
    price: 285,
  ),
  Hotel(
    name: 'Luxurious',
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/465288867.jpg?k=e59b50776354bf7d758b2a943d6ff696933db4979a709b0a3e5127e115804718&o=&hp=1',
    description: 'Luxurious 2 BR, 2 BA - Aspen Core has a patio and is located in Aspen, within just a 3-minute walk of Aspen Art Museum and 300 yards of Isis Theatre. The property is a 4-minute walk from the The John Denver Sanctuary and features free Wifithroughout the property.\n\nThe vacation home features 2 bedrooms, a fully equipped kitchen with a dishwasher and an oven, and 2 bathrooms with a hot tub and a hair dryer. Towels and bed linen are featured in the vacation home.',
    type: '2N/1D',
    category: 'Pleasent',
    rating: 4.8,
    reviews:288,
    price: 280,
  ),
];